# Generated by Django 2.2.16 on 2021-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211206_1809'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('User', 'following'), name='Unique_name_follow'),
        ),
    ]
